### ISSUE TITLE
Starting from Bam files

### ISSUE THREAD

**Issue by npatel-ah** [WenjinGudaisy/SearcHPV#4]
Hello, 

I was wondering if it's possible to skip the alignment step and start from the next step. We've pipeline that create a markduplicated bam files  using Illumina Dragen Pipeline and would like to use it for the remaining of the analysis. 

Thanks

**Comment by WenjinGudaisy** [comment]
Hi,
For the step3 and step4, fastq files are still needed as we extract reads from fastq for the local assembly. You could try to run it and get a preliminary results of integrations from step2:
1. change the file name as "alignment.RG.indelre.mkdup.sort.bam"
2. index it and also put the two files under the folder "[your work dir]/alignment/". 
3. Catenate the references: 

> cat {humRef} {virRef} > [your work dir]/hg_hpv.fa

5. Index the references: 

> bwa index {ref}

> samtools faidx {ref}

> picard CreateSequenceDictionary R={ref} O={ref.replace('.fa','.dict')

8. Run the second step: 

> SearcHPV -fastq1 1.fastq.gz[give it a name but it won't be used]-fastq2 2.fastq.gz -humRef your_ref.fa -virRef your_ref_virus.fa -output [your work dir] -genomeFusion

Your result will be in a file called: "{your work dir}/{virus_chrm}.all.filtered.clustered.result"

**Comment by npatel-ah** [comment]
Awesome thank you so much for your detailed response.
